version: '2'
services:

  auth:
    image: registry.jincor.com/backend/auth:latest
    build:
        context: ./
        dockerfile: Dockerfile.prod
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      FORCE_HTTPS: disabled
      JWT_KEY: "uZrJ!xe*xN?!;oU.u*;QOSM+|=4C?WH?6eWPcK/6AkIXIVGQguSA*r"
    ports:
      - "3000"
      - "4000"
    volumes:
      - ./:/usr/src/app
    links:
      - redis

  redis:
    image: registry.jincor.com/backend/redis:latest
    ports:
      - "6379"
